# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20170825_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_status',
            new_name='status',
        ),
    ]
